#!/bin/bash

ipstart="192.168.0"
myip=`ifconfig | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | egrep -v "255.|^127.|\.255" |cut -d'.' -f1-3`

echo "myip= $myip"

End=35
ipstart=$myip

[ -n "$1" ] && ipstart=$1
[ -n "$2" ] && End=$2 

for ((i=1;i<$End;i++)) ; do
   x="$ipstart.$i"
   ( ping -c1 -w1 $x | grep "bytes from " | grep -o "$x" & )
done

echo ""
